# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170223_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fomouser',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
