# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkproduct',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bulkproduct',
            name='reorder_point',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bulkproduct',
            name='reorder_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
