# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170228_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpicture',
            name='alttext',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productpicture',
            name='mimetype',
            field=models.TextField(null=True),
        ),
    ]
