# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170307_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicture',
            name='is_primary',
            field=models.NullBooleanField(),
        ),
    ]
