# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productpicture_is_primary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPicture',
            new_name='ProductImage',
        ),
    ]
