# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_shoppingcart_shoppinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('qty_updated_date', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('remove_date', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_item', to='catalog.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='qty_updated_date',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='remove_date',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='shopping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.ShoppingCart'),
        ),
    ]
