# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170329_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproduct',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uniqueproduct',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
