# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20170331_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_item_type',
            field=models.CharField(default='PRODUCT', max_length=50),
        ),
    ]
