# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_saleitem_sale_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_item_type', models.CharField(default='PRODUCT', max_length=50)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='catalog.Sale')),
            ],
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
