# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20170401_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelineitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='catalog.Sale'),
        ),
    ]
